### ISSUE TITLE
git-bzr-ng branch tries to allocate awesome amount of memory

### ISSUE THREAD

**Issue by dcolascione** [termie/git-bzr-ng#42]
22:45:57 118000/122118 commits exported at 944/minute 
22:50:21 119000/122118 commits exported at 919/minute 
22:54:05 120000/122118 commits exported at 901/minute 
22:54:05 Exported 120000 commits - adding checkpoint to output
22:56:21 121000/122118 commits exported at 893/minute 
22:57:22 122000/122118 commits exported at 894/minute 
22:57:29 WARNING: not creating tag u'EMACS_23_1' pointing to non-existent revision cyd@stupidchicken.com-20090730011415-1ur84cd4r2dats1v
22:57:29 WARNING: not creating tag u'EMACS_PRETEST_23_0_96' pointing to non-existent revision cyd@stupidchicken.com-20090709001437-w4jk00hlmj3epguj
22:57:29 Exported 122118 revisions in 2:16:35
DEBUG:root:captured output (bzr fast-export):
python(60661) malloc: **\* mmap(size=140780772814848) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "/Users/danielcolascione/bin/git-bzr", line 709, in <module>
    sys.exit(main(sys.argv))
  File "/Users/danielcolascione/bin/git-bzr", line 703, in main
    return func(argv[2:])
  File "/Users/danielcolascione/bin/git-bzr", line 417, in cmd_clone
    cmd_import(args)
  File "/Users/danielcolascione/bin/git-bzr", line 589, in cmd_import
    export_bzr(bzr_ref, cl=cl)
  File "/Users/danielcolascione/bin/git-bzr", line 282, in export_bzr
    git_proc_in.close()
  File "/Users/danielcolascione/bin/git-bzr", line 150, in close
    rv = self._io.read()
MemoryError

**Comment by dcolascione** [comment]
Err, reading the code, the problem was that I was running with debugging turned on. I guess the real bug here is that LoggingPipe._capture shouldn't be turned on just because debug logging is enabled.
