### ISSUE TITLE
git bzr push after github merge fails

### ISSUE THREAD

**Issue by ywwg** [termie/git-bzr-ng#57]
```
15:18:02 Calculating the revisions to include ...
15:18:02 Starting export of 8615 revisions ...
15:18:02 Exported 8615 revisions in 0:00:00
warning: Not updating refs/tags/release180 (new tip 235ab930f203929d9ef3ea1482deed167f58e3b5 does not contain 508b8e6b82a1b03141ae81557f1fadb137531345)
warning: Not updating refs/tags/release181 (new tip 4dbdb8ba9475c699b9c10c4cbbf964175bf327d7 does not contain 30e2e8177e6eb4830fb48022c74b604bd4d09bb3)
warning: Not updating refs/tags/release180beta2 (new tip d088beed52ed3947df1991aeeaecdb5b26135318 does not contain 9420e89a1e840f13b37246ea82a439a3f6626d1f)
15:18:02 Starting import ...
15:18:02 Updating branch information ...
bzr: ERROR: exceptions.KeyError: '8620'

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 930, in exception_to_return_code
    return the_callable(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 1121, in run_bzr
    ret = run(*run_argv)
  File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 673, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 697, in run
    return self._operation.run_simple(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/cleanup.py", line 136, in run_simple
    self.cleanups, self.func, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/cleanup.py", line 166, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/fastimport/cmds.py", line 307, in run
    user_map=user_map)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/fastimport/cmds.py", line 39, in _run
    return proc.process(p.iter_commands)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/fastimport/processors/generic_processor.py", line 310, in process
    super(GenericProcessor, self)._process(command_iter)
  File "/usr/lib/python2.7/dist-packages/fastimport/processor.py", line 79, in _process
    self.post_process()
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/fastimport/processors/generic_processor.py", line 351, in post_process
    branches_updated, branches_lost = updater.update()
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/fastimport/branch_updater.py", line 61, in update
    if self._update_branch(br, tip):
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/fastimport/branch_updater.py", line 153, in _update_branch
    last_rev_id = self.cache_mgr.lookup_committish(last_mark)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/fastimport/cache_manager.py", line 134, in lookup_committish
    return self.marks[committish.lstrip(':')]
KeyError: '8620'

bzr 2.6.0dev3 on python 2.7.4 (Linux-3.8.0-19-generic-x86_64-with-
    Ubuntu-13.04-raring)
arguments: ['/usr/bin/bzr', 'fast-import', '--import-
    marks=/home/owen/src/github/mixxx-official/mixxx/.git/bzr/map/master-bzr',
    '--export-marks=/home/owen/src/github/mixxx-official/mixxx/.git/bzr/map
    /master-bzr', '-', '/home/owen/src/github/mixxx-
    official/mixxx/.git/bzr/repo/master']
plugins: bash_completion[2.6.0dev3], bzrtools[2.5.0],
    changelog_merge[2.6.0dev3], extmerge[unknown], fastimport[0.13.0],
    grep[2.6.0dev3], launchpad[2.6.0dev3], netrc_credential_store[2.6.0dev3],
    news_merge[2.6.0dev3], pager[unknown], po_merge[2.6.0dev3],
    weave_fmt[2.6.0dev3], xmloutput[0.8.8]
encoding: 'utf-8', fsenc: 'UTF-8', lang: 'en_US.UTF-8'

*** Bazaar has encountered an internal error.  This probably indicates a
    bug in Bazaar.  You can help us fix it by filing a bug report at
        https://bugs.launchpad.net/bzr/+filebug
    including this traceback and a description of the problem.
ERROR:root:bzr import failed
```

My git marks file has the 8620 key:

```
git bzr marks |grep \:8620
:8620 2b021f70df447f08abb8a0ed298cc6fbe0948a7a
```

but bzr doesn't:
    cat /home/owen/src/github/mixxx-official/mixxx/.git/bzr/map/master-bzr |grep 8620
(no output)

here's the log -- the last three commits are new, the fourth is lp:mixxx HEAD

```
commit 2b021f70df447f08abb8a0ed298cc6fbe0948a7a
Merge: 66ca850 7253f13
Author: Owen Williams <owilliams@mixxx.org>
Date:   Tue May 14 09:04:49 2013 -0700

    Merge pull request #1 from ywwg/loopfix

    If quantize is on, don't possibly choose the next beat because that will cause a seek

commit 7253f13051379a0170fcd1e1a43fe4962f9ac8b7
Author: Owen Williams <owen-github@ywwg.com>
Date:   Sat May 11 16:39:11 2013 -0400

    Add clarifying comment.

commit e0ba509009e3ef398787972f136297ddd9c00608
Author: Owen Williams <owen-github@ywwg.com>
Date:   Sat May 11 01:49:05 2013 -0400

    If quantize is on, don't possibly choose the next beat because that will cause a seek

commit 66ca8502ec9e01a610e3854823f1a5a7f67baba6
Author: Max Linke <kain88@mixxx.org>
Date:   Sun May 12 12:15:29 2013 +0200

    remove old BPM analyser code, Fix Bug #1179038

commit 35c2bd64743f7097d7536922fa5a8ae552d5fab7
Author: jus <s.brandt@mixxx.org>
Date:   Thu May 9 15:26:29 2013 +0200

    Update translation templates for https://translations.launchpad.net/mixxx/trunk
```

**Comment by vinipsmaker** [comment]
I can reproduce the bug too:

```
03:27:50 Calculating the revisions to include ...
03:27:51 Starting export of 13954 revisions ...
03:27:51 WARNING: not creating tag u'INKSCAPE_0_48_1' pointing to non-existent revision ted@gould.cx-20110127043742-xzd3vv5ym0asxp0g
03:27:51 WARNING: not creating tag u'INKSCAPE_0_48_2' pointing to non-existent revision ted@gould.cx-20110708192754-opri228tl6h6isl3
03:27:51 Exported 13954 revisions in 0:00:01
03:27:51 Starting import ...
03:27:51 Updating branch information ...
bzr: ERROR: exceptions.KeyError: '13956'

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 930, in exception_to_return_code
    return the_callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 1121, in run_bzr
    ret = run(*run_argv)
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 673, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/usr/lib/python2.7/site-packages/bzrlib/commands.py", line 697, in run
    return self._operation.run_simple(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/cleanup.py", line 136, in run_simple
    self.cleanups, self.func, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/cleanup.py", line 166, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bzrlib/plugins/fastimport/cmds.py", line 307, in run
    user_map=user_map)
  File "/usr/lib/python2.7/site-packages/bzrlib/plugins/fastimport/cmds.py", line 39, in _run
    return proc.process(p.iter_commands)
  File "/usr/lib/python2.7/site-packages/bzrlib/plugins/fastimport/processors/generic_processor.py", line 310, in process
    super(GenericProcessor, self)._process(command_iter)
  File "/usr/lib/python2.7/site-packages/fastimport/processor.py", line 79, in _process
    self.post_process()
  File "/usr/lib/python2.7/site-packages/bzrlib/plugins/fastimport/processors/generic_processor.py", line 351, in post_process
    branches_updated, branches_lost = updater.update()
  File "/usr/lib/python2.7/site-packages/bzrlib/plugins/fastimport/branch_updater.py", line 61, in update
    if self._update_branch(br, tip):
  File "/usr/lib/python2.7/site-packages/bzrlib/plugins/fastimport/branch_updater.py", line 153, in _update_branch
    last_rev_id = self.cache_mgr.lookup_committish(last_mark)
  File "/usr/lib/python2.7/site-packages/bzrlib/plugins/fastimport/cache_manager.py", line 134, in lookup_committish
    return self.marks[committish.lstrip(':')]
KeyError: '13956'

bzr 2.6.0 on python 2.7.6 (Linux-3.12.9-2-ARCH-x86_64-with-glibc2.2.5)
arguments: ['/usr/bin/bzr', 'fast-import', '--import-
    marks=/media/Avalon/Vini/Projetos/inkscape/.git/bzr/map/master-bzr',
    '--export-marks=/media/Avalon/Vini/Projetos/inkscape/.git/bzr/map/master-
    bzr', '-', '/media/Avalon/Vini/Projetos/inkscape/.git/bzr/repo/master']
plugins: bash_completion[2.6.0], changelog_merge[2.6.0], fastimport[0.13.0],
    grep[2.6.0], launchpad[2.6.0], netrc_credential_store[2.6.0],
    news_merge[2.6.0], po_merge[2.6.0], weave_fmt[2.6.0]
encoding: 'utf-8', fsenc: 'UTF-8', lang: 'pt_BR.UTF-8'

*** Bazaar has encountered an internal error.  This probably indicates a
    bug in Bazaar.  You can help us fix it by filing a bug report at
        https://bugs.launchpad.net/bzr/+filebug
    including this traceback and a description of the problem.
ERROR:root:bzr import failed
```

I'm using an ArchLinux system with git-bzr-ng version 9878a30.

**Comment by Manuel-Kehl** [comment]
I am also affected by this. 
Is there any way to work around this?

**Comment by vinipsmaker** [comment]
@mank319, you can use [git-fc](https://github.com/felipec/git).

**Comment by Manuel-Kehl** [comment]
@vinipsmaker thanks for the hint!
