### ISSUE TITLE
Pushing branch with local change fails under Ubuntu 10.10

### ISSUE THREAD

**Issue by hrw** [termie/git-bzr-ng#9]
I cloned bzr repository, did some changes and can not push those changes back to launchpad.

<pre>
$ git bzr clone http://bazaar.launchpad.net/~hrw/ubuntu/maverick/armel-cross-toolchain-base/binutils-no-sysroot/  test
$ git bzr push lp:~hrw/+junk/test
11:07:52 Starting import ...
Created new branch.\ Fetching revisions:Finishing stream:Estimate 7/1421

11:09 hrw@home:test$ git commit . -m"test commit"
[master 7b0d149] test commit
 1 files changed, 6 insertions(+), 0 deletions(-)
11:09 hrw@home:test$ git bzr push lp:~hrw/+junk/test
11:09:33 Calculating the revisions to include ...m source
11:09:33 Starting export of 138 revisions ...
11:09:33 Exported 138 revisions in 0:00:00
11:09:34 Starting import ...
bzr: ERROR: exceptions.IndexError: list index out of range

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/bzrlib/commands.py", line 911, in exception_to_return_code
    return the_callable(*args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/bzrlib/commands.py", line 1111, in run_bzr
    ret = run(*run_argv)
  File "/usr/lib/python2.6/dist-packages/bzrlib/commands.py", line 689, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/usr/lib/python2.6/dist-packages/bzrlib/commands.py", line 704, in run
    return self._operation.run_simple(*args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/bzrlib/cleanup.py", line 135, in run_simple
    self.cleanups, self.func, *args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/bzrlib/cleanup.py", line 165, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/__init__.py", line 384, in run
    params, verbose, user_map=user_map)
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/__init__.py", line 111, in _run
    return proc.process(p.iter_commands)
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/processor.py", line 95, in process
    self._process(command_iter)
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/processors/generic_processor.py", line 283, in _process
    processor.ImportProcessor._process(self, command_iter)
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/processor.py", line 117, in _process
    handler(self, cmd)
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/processors/generic_processor.py", line 493, in commit_handler
    handler.process()
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/processor.py", line 200, in process
    self.pre_process_files()
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/bzr_commit_handler.py", line 582, in pre_process_files
    super(InventoryDeltaCommitHandler, self).pre_process_files()
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/bzr_commit_handler.py", line 91, in pre_process_files
    self.revision = self.build_revision()
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/bzr_commit_handler.py", line 227, in build_revision
    self.branch_ref)
  File "/usr/lib/python2.6/dist-packages/bzrlib/plugins/fastimport/branch_mapper.py", line 39, in git_to_bzr
    name_no_ext = self._git_to_bzr_name(parts[-1])
IndexError: list index out of range

You can report this problem to Bazaar's developers by running
    apport-bug /var/crash/bzr.1000.2010-10-07T09:09.crash
if a bug-reporting window does not automatically appear.
No new revisions to push.
</pre>

**Comment by hrw** [comment]
pushing to new bzr branch works - only pushing to existing ones does not

**Comment by termie** [comment]
I think this may be resolved:

<pre>
(git-bzr-ng)termie@chester:~/p/tmp % git bzr clone lp:~termie/+junk/lala                                                 15:41:35
Branched 1 revision(s).tching revisions:Finishing stream:Done 10/10
15:41:53 Calculating the revisions to include ...
15:41:53 Starting export of 1 revisions ...
15:41:53 Exported 1 revision in 0:00:00
Already on 'master'
(git-bzr-ng)termie@chester:~/p/tmp % cd lala                                                                             15:41:53
(git-bzr-ng)termie@chester:p/tmp/lala % ls                                                                      [master] 15:41:55
lala.txt
(git-bzr-ng)termie@chester:p/tmp/lala % vim lala.txt                                                            [master] 15:41:55
(git-bzr-ng)termie@chester:p/tmp/lala % git commit -m "asdasd"                                                  [master] 15:42:01
# On branch master
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   lala.txt
#
no changes added to commit (use "git add" and/or "git commit -a")
(git-bzr-ng)termie@chester:p/tmp/lala % git commit -a -m "asdasd"                                               [master] 15:42:04
[master 39371e2] asdasd
 1 files changed, 1 insertions(+), 0 deletions(-)
(git-bzr-ng)termie@chester:p/tmp/lala % git bzr push                                                            [master] 15:42:11
15:42:24 Calculating the revisions to include ...
15:42:24 Starting export of 1 revisions ...
15:42:24 Exported 1 revision in 0:00:00
15:42:24 Starting import ...
15:42:24 Updating branch information ...
     branch master now has 2 revisions and 0 tags
15:42:24 Packing repository ...
15:42:24 Removing obsolete packs ...
15:42:24 Imported 1 revision, updating 1 branch and 0 trees in 0:00:00
To refresh the working tree for other branches, use 'bzr update' inside that branch.
Pushed up to revision 2.ching revisions:Finishing stream:Done 10/10
(git-bzr-ng)termie@chester:p/tmp/lala %     
</pre>
